project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

bibliography: references.bib

book:
  title: "Political Party Impact"
  author:
    - Ava Grey (ag4378)
  repo-url: https://github.com/avagreyyy4/political-party-impact
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd
    - references.bib

format:
  html:
    theme: lux
    code-fold: true


